import { fakerEN_IN as faker } from '@faker-js/faker'
import * as fs from 'fs'

const CITIES = ['Delhi', 'Mumbai', 'Bengaluru', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Ahmedabad']

function escapeStr(str: string) {
  return str.replace(/'/g, "''")
}

function formatDate(date: Date) {
  return date.toISOString()
}

function generateSql() {
  const customerData = Array.from({ length: 500 }, (_, i) => ({
    id: faker.string.uuid(),
    name: faker.person.fullName(),
    email: `customer_${i}_${faker.string.alphanumeric(4)}@example.com`,
    phone: `+91${faker.string.numeric(10)}`,
    city: faker.helpers.arrayElement(CITIES),
    total_spent: 0,
    order_count: 0,
    created_at: faker.date.past({ years: 2 })
  }))

  const totals: Record<string, { spent: number; count: number; lastOrder: Date }> = {}
  const orderData: any[] = []

  for (let i = 0; i < 2000; i++) {
    const customer = faker.helpers.arrayElement(customerData)
    const amount = parseFloat(faker.commerce.price({ min: 200, max: 15000 }))
    const createdAt = faker.date.between({ from: customer.created_at, to: new Date() })

    if (!totals[customer.id]) totals[customer.id] = { spent: 0, count: 0, lastOrder: createdAt }
    
    if (faker.helpers.arrayElement(['completed', 'completed', 'completed', 'refunded']) === 'completed') {
      totals[customer.id].spent += amount
      totals[customer.id].count += 1
      if (createdAt > totals[customer.id].lastOrder) totals[customer.id].lastOrder = createdAt
    }

    orderData.push({
      id: faker.string.uuid(),
      customer_id: customer.id,
      amount,
      items: [{ name: faker.commerce.productName(), qty: faker.number.int({ min: 1, max: 4 }), price: amount }],
      status: 'completed',
      created_at: createdAt
    })
  }

  // Update customer aggregates
  for (const customer of customerData) {
    if (totals[customer.id]) {
      customer.total_spent = parseFloat(totals[customer.id].spent.toFixed(2))
      customer.order_count = totals[customer.id].count
      // @ts-ignore
      customer.last_order_at = totals[customer.id].lastOrder
    }
  }

  let sql = `-- Seed Script generated by agent\n`
  // Delete all existing data
  sql += `DELETE FROM "communication_events";\n`
  sql += `DELETE FROM "communications";\n`
  sql += `DELETE FROM "orders";\n`
  sql += `DELETE FROM "campaigns";\n`
  sql += `DELETE FROM "segments";\n`
  sql += `DELETE FROM "customers";\n\n`

  sql += `-- Insert customers\n`
  const customerChunks = []
  for (let i = 0; i < customerData.length; i += 100) {
    const chunk = customerData.slice(i, i + 100)
    const values = chunk.map(c => `('${c.id}', '${escapeStr(c.name)}', '${escapeStr(c.email)}', '${escapeStr(c.phone)}', '${escapeStr(c.city)}', ${c.total_spent}, ${c.order_count}, '${formatDate(c.created_at)}', ${// @ts-ignore
      c.last_order_at ? `'${formatDate(c.last_order_at)}'` : 'NULL'})`).join(',\n')
    customerChunks.push(`INSERT INTO "customers" ("id", "name", "email", "phone", "city", "total_spent", "order_count", "created_at", "last_order_at") VALUES\n${values};`)
  }
  sql += customerChunks.join('\n\n') + '\n\n'

  sql += `-- Insert orders\n`
  const orderChunks = []
  for (let i = 0; i < orderData.length; i += 100) {
    const chunk = orderData.slice(i, i + 100)
    const values = chunk.map(o => `('${o.id}', '${o.customer_id}', ${o.amount}, '${JSON.stringify(o.items)}'::jsonb, '${o.status}', '${formatDate(o.created_at)}')`).join(',\n')
    orderChunks.push(`INSERT INTO "orders" ("id", "customer_id", "amount", "items", "status", "created_at") VALUES\n${values};`)
  }
  sql += orderChunks.join('\n\n') + '\n\n'

  sql += `-- Insert segments\n`
  sql += `INSERT INTO "segments" ("id", "name", "filter_definition", "customer_count") VALUES\n`
  sql += `('${faker.string.uuid()}', 'High Value Customers', '{"combinator": "AND", "rules": [{"field": "total_spent", "operator": "gte", "value": 10000}]}'::jsonb, 0),\n`
  sql += `('${faker.string.uuid()}', 'Dormant Customers', '{"combinator": "AND", "rules": [{"field": "last_order_at", "operator": "days_ago_gt", "value": 60}]}'::jsonb, 0),\n`
  sql += `('${faker.string.uuid()}', 'Mumbai Shoppers', '{"combinator": "AND", "rules": [{"field": "city", "operator": "eq", "value": "Mumbai"}]}'::jsonb, 0);\n`

  fs.writeFileSync('seed.sql', sql)
  console.log('Generated seed.sql')
}

generateSql()
